name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Runs on direct pushes and merges into master
  pull_request:
    branches:
      - master
    types:
      - closed  # Runs when a pull request is merged into master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build  # Ensure this matches your build command

      - name: Move Build Files to Root
        run: |
          rm -rf .gitignore .github
          mv dist/* .  # Move built files to root
          rm -rf dist  # Remove the now-empty dist folder

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "🚀 Deploy to GitHub Pages"
          git push